[build]

  # Directory of Built Files

  publish = "Dist/"

  # Production Build Command

  command = "npm run prod"

  # Directory with the Lambda functions to deploy to AWS

  functions = "Lambda/"

[dev]

  # Development Build Command

#  framework = "#custom"
  command = "./netlify-dev.sh"

  # Webpack-Dev-Server Port

  targetPort = 3000

  publish = "Dist/"
  autoLaunch = true

[[redirects]]

#   For React Router

  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]

  for = "/*"

  # Security Is Good

  [headers.values]

      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "SAMEORIGIN"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "same-origin"

